server:
  port: 8080 # 项目启动端口

spring:
  profiles:
    active: dev
  cassandra:
    contact-points: 192.168.5.200 # Cassandra 集群节点地址（可配置多个，用逗号分隔）
    port: 9042 # 端口号
    local-datacenter: datacenter1 # 必须与集群配置的数据中心名称一致（大小写敏感）
  ai:
    chat:
      memory:
        repository:
          cassandra:
            keyspace: slilio_ai_robot # 指定存储聊天记忆的 Keyspace（类似数据库名）
            table: t_ai_chat_memory # 表名
            time-to-live: 1095d # 数据的自动过期时间（1095天 ≈ 3年）
            initialize-schema: true  # 自动初始化表结构
    deepseek:
      api-key: ${spring.ai.deepseek.api-key} # 填写 DeepSeek Api Key
      base-url: https://api.deepseek.com # DeepSeek 的请求 URL, 可不填，默认值为 api.deepseek.com
      chat:
        options:
          model: deepseek-chat # 使用哪个模型 #v3模型
          #          model: deepseek-reasoner #r1模型
          temperature: 0.8 # 温度值
    ollama:
      base-url: http://localhost:11434 # Ollama 服务的访问地址, 11434 端口是 Ollama 默认的启动端口
      chat:
        options: # 模型参数
          model: qwen3:1.7b # 指定 Ollama 使用的大模型名称，根据你实际安装的来，我运行的是 14b
          temperature: 0.7 # 温度值
    zhipuai:
      base-url: https://open.bigmodel.cn/api/paas # 智谱 AI 的请求 URL, 可不填，默认值为 open.bigmodel.cn/api/paas
      api-key: ${spring.ai.zhipuai.api-key} # 填写智谱 AI 的 API Key
      chat:
        options: # 模型参数
          model: glm-4-plus # 模型名称，使用智谱 AI 哪个模型
          temperature: 0.7 # 温度值
    #注释掉，使用阿里的ai，依赖依旧是openai
    #    openai:
    #      #      base-url: https://api.zhizengzeng.com/v1 # OpenAI 服务的访问地址，这里使用的第三方代理商智增增
    #      #      api-key: ${spring.ai.openai.api-key}  # 填写智增增的 API Key
    #      base-url: https://api.gptgod.online      # OpenAI 服务的访问地址，这里使用的第三方代理商：GptGod
    #      api-key: ${spring.ai.openai.api-key}  # 填写智增增的 API Key
    #      chat:
    #        options:
    #          model: gpt-4o-mini # 模型名称
    #          temperature: 0.7 # 温度值
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode # OpenAI 服务的访问地址，这里使用的是阿里云百炼
      api-key: ${spring.ai.openai.api-key}  # 填写阿里云百炼的 API Key, 该成你自己的
      chat:
        options:
          model: qwen-omni-turbo # 模型名称
          temperature: 0.7 # 温度值
